export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "createdAt" TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS food_items (
    id TEXT NOT NULL,
    "userId" TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    brand TEXT,
    barcode TEXT,
    "servingSize" DOUBLE PRECISION NOT NULL,
    "servingUnit" TEXT NOT NULL,
    source TEXT NOT NULL,
    "sourceId" TEXT,
    calories DOUBLE PRECISION NOT NULL DEFAULT 0,
    "proteinG" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "carbsG" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "fatG" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "fiberG" DOUBLE PRECISION,
    "sugarG" DOUBLE PRECISION,
    "sodiumMg" DOUBLE PRECISION,
    "createdAt" TEXT NOT NULL,
    "updatedAt" TEXT NOT NULL,
    PRIMARY KEY ("userId", id)
  );`,
  `CREATE TABLE IF NOT EXISTS meal_entries (
    id TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    "foodItemId" TEXT NOT NULL,
    "mealType" TEXT NOT NULL,
    date TEXT NOT NULL,
    servings DOUBLE PRECISION NOT NULL DEFAULT 1,
    notes TEXT,
    "createdAt" TEXT NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS meal_entries_user_date_idx ON meal_entries("userId", date);`,
  `CREATE TABLE IF NOT EXISTS user_profile (
    "userId" TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    age INTEGER,
    sex TEXT,
    "heightCm" DOUBLE PRECISION,
    "currentWeightKg" DOUBLE PRECISION,
    "targetWeightKg" DOUBLE PRECISION,
    "goalType" TEXT NOT NULL,
    "activityMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.2,
    "createdAt" TEXT NOT NULL,
    "updatedAt" TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS health_connections (
    id TEXT PRIMARY KEY,
    "userId" TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    "providerUserId" TEXT,
    status TEXT NOT NULL,
    scopes TEXT,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "expiresAt" TEXT,
    "lastSyncedAt" TEXT,
    "createdAt" TEXT NOT NULL,
    "updatedAt" TEXT NOT NULL
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS health_connections_user_provider_idx ON health_connections("userId", provider);`,
  `CREATE TABLE IF NOT EXISTS health_metrics_daily (
    "userId" TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date TEXT NOT NULL,
    provider TEXT NOT NULL,
    steps INTEGER,
    "activeEnergyKcal" DOUBLE PRECISION,
    "totalEnergyKcal" DOUBLE PRECISION,
    "weightKg" DOUBLE PRECISION,
    "sleepMinutes" INTEGER,
    "sleepScore" DOUBLE PRECISION,
    "readinessScore" DOUBLE PRECISION,
    "restingHeartRate" DOUBLE PRECISION,
    "hrvMs" DOUBLE PRECISION,
    "spo2Pct" DOUBLE PRECISION,
    workouts INTEGER,
    PRIMARY KEY ("userId", date, provider)
  );`,
] as const;
